apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: connectionpool-sandbox
spec:
  selector:
    matchLabels:
      app: tempo
  replicas: 1
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.3.1
          args: ["-config.file=/etc/tempo/tempo.yaml"]
          ports:
            - containerPort: 3100  # HTTP API
            - containerPort: 4318  # OTLP HTTP
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
      volumes:
        - name: config
          configMap:
            name: tempo-config
