apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyroscope
  namespace: connectionpool-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyroscope
  template:
    metadata:
      labels:
        app: pyroscope
    spec:
      containers:
        - name: pyroscope
          image: grafana/pyroscope:latest
          ports:
            - containerPort: 4040
          args:
            - "server"
          readinessProbe:
            httpGet:
              path: /ready
              port: 4040
            initialDelaySeconds: 5
            periodSeconds: 5
