adminPassword: admin

grafana.ini:
  auth.anonymous:
    enabled: true
    org_role: Admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        uid: influxdb
        url: http://influxdb:8086
        database: k6
        isDefault: false
        jsonData:
          version: InfluxQL
          httpMode: GET
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus-server:80
        isDefault: true
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo:3100
        isDefault: false

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboardsConfigMaps:
  default: grafana-dashboards
