apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: connectionpool-sandbox
spec:
  selector:
    app: mysql-exporter
  ports:
    - port: 9104
      targetPort: 9104
  type: ClusterIP
